### ISSUE TITLE
Start-up: No module named 'llmstudio.engine'

### ISSUE THREAD

**Issue by ghost** [TensorOpsAI/LLMstudio#58]
### System Info

Unable to launch LLMStudio in pycharm environment on Windows server.

$ LLMStudio server
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\pythonProject-LLMStudio\venv\Scripts\LLMStudio.exe\__main__.py", line 4, in <module>
  File "C:\pythonProject-LLMStudio\venv\lib\site-packages\llmstudio\cli.py", line 3, in <module>
    from llmstudio.engine.config import EngineConfig
ModuleNotFoundError: No module named 'llmstudio.engine'

### Related Components

- [ ] API
- [X] SDK
- [ ] UI

### Reproduction

1. Install LLMStudio (pip install LLMStudio)
2. launch the LLMServer (LLMStudio server)
3. Error is observed

### Expected behavior

The LLMStudio server should start and should be able to connect on localhost.

**Comment by MiNeves00** [comment]
Issue might be related to #61, we are currently working on it. After #61 is fixed I will ask you to test again if the bug still persists.
